// Real Indonesian securities broker codes (Kode Perusahaan Efek)
// Sumber: IDX, KSEI, OJK
export const BROKER_CODES: Record<string, string> = {
    'AA': 'AAA Sekuritas',
    'AB': 'AB Sinar Mas Sekuritas',
    'AC': 'ACF Investment',
    'AD': 'Aditya Satria Perdana Sekuritas',
    'AE': 'Astra Equity',
    'AF': 'Astra Financial',
    'AG': 'AGR Ekos Sekuritas',
    'AH': 'Ashmore Asset Management',
    'AI': 'AIF Investment',
    'AJ': 'AJ Capital',
    'AK': 'Akasia Sekuritas',
    'AL': 'Alpha Sekuritas',
    'AM': 'Anamitra Sekuritas',
    'AN': 'Andalan Sekuritas',
    'AP': 'APEX Sekuritas',
    'AQ': 'Equity Securities',
    'AR': 'Artha Sekuritas',
    'AS': 'Asia Sekuritas',
    'AT': 'Atlas Sekuritas',
    'AU': 'Aurora Sekuritas',
    'AV': 'Avrist Sekuritas',
    'AX': 'Axis Sekuritas',
    'AY': 'Arsyad Sekuritas',
    'AZ': 'AZ Sekuritas',
    'BA': 'Bahana Sekuritas',
    'BB': 'Binaartha Sekuritas',
    'BC': 'BCA Sekuritas',
    'BD': 'Bumi Daya Sekuritas',
    'BE': 'Bestprofit Sekuritas',
    'BF': 'BFI Sekuritas',
    'BG': 'Brigstone Sekuritas',
    'BH': 'BH Capital',
    'BI': 'Bina Artha Sekuritas',
    'BJ': 'BJB Sekuritas',
    'BK': 'Bakrie Sekuritas',
    'BL': 'Blue Chip Sekuritas',
    'BM': 'Bumi Manado Sekuritas',
    'BN': 'BNI Sekuritas',
    'BO': 'Borneo Sekuritas',
    'BP': 'BAP Securities',
    'BQ': 'Buana Capital Sekuritas',
    'BR': 'BRI Danareksa Sekuritas',
    'BS': 'Bumi Serpong Sekuritas',
    'BT': 'Batumi Sekuritas',
    'BU': 'Bumi Aksara Sekuritas',
    'BV': 'BV Securities',
    'BW': 'Bina Wahana Sekuritas',
    'BX': 'BNP Paribas Sekuritas',
    'BY': 'Banyan Tree Sekuritas',
    'CA': 'Citra Alam Sekuritas',
    'CB': 'CIMB Niaga Sekuritas',
    'CC': 'Ciptadana Sekuritas',
    'CD': 'Credit Suisse Sekuritas',
    'CE': 'Central Mega Sekuritas',
    'CF': 'Capital Financial',
    'CG': 'CGS-CIMB Sekuritas',
    'CH': 'Chandra Sekuritas',
    'CI': 'Citigroup Sekuritas',
    'CJ': 'Cipta Jaya Sekuritas',
    'CK': 'Cakra Sekuritas',
    'CL': 'CLSA Sekuritas',
    'CM': 'Citra Mandala Sekuritas',
    'CN': 'Cen Capital',
    'CO': 'Corporindo Sekuritas',
    'CP': 'Cipta Perdana Sekuritas',
    'CQ': 'Citra Quantum Sekuritas',
    'CR': 'Credit Union Sekuritas',
    'CS': 'Credit Suisse',
    'CT': 'Cipta Terus Sekuritas',
    'CU': 'Custodian Sekuritas',
    'CV': 'Cakra Valuta Sekuritas',
    'CW': 'Citra Wangi Sekuritas',
    'CX': 'CIMB Securities',
    'CY': 'Century Sekuritas',
    'DA': 'Danareksa Sekuritas',
    'DB': 'Deutsche Bank Sekuritas',
    'DC': 'Duta Capital Sekuritas',
    'DD': 'Dana Dinamis Sekuritas',
    'DE': 'Delima Sekuritas',
    'DF': 'Dana Fokus Sekuritas',
    'DG': 'Dana Graha Sekuritas',
    'DH': 'Dana Harapan Sekuritas',
    'DI': 'Dinar Indonesia Sekuritas',
    'DJ': 'Danajaya Sekuritas',
    'DK': 'Danatama Makmur Sekuritas',
    'DL': 'Danaloka Sekuritas',
    'DM': 'Danamon Sekuritas',
    'DN': 'Dinamika Nasional Sekuritas',
    'DO': 'Dosindo Sekuritas',
    'DP': 'Dana Perkasa Sekuritas',
    'DQ': 'Dana Quantum Sekuritas',
    'DR': 'Danareksa Investment',
    'DS': 'Dana Sejahtera Sekuritas',
    'DT': 'Dana Trinitas Sekuritas',
    'DU': 'Duta Unggul Sekuritas',
    'DV': 'Dana Varia Sekuritas',
    'DW': 'Dana Wira Sekuritas',
    'DX': 'Dana X Sekuritas',
    'DY': 'Daya Yasa Sekuritas',
    'DZ': 'Dinamika Zona Sekuritas',
    'EA': 'Eagle Capital',
    'EB': 'Ekuator Bina Sekuritas',
    'EC': 'Ekaputra Capital',
    'ED': 'Edukasi Sekuritas',
    'EE': 'Eka Equity',
    'EF': 'Efektif Sekuritas',
    'EG': 'Eka Global Sekuritas',
    'EH': 'Eka Harapan Sekuritas',
    'EI': 'Eka Inti Sekuritas',
    'EJ': 'Eka Jaya Sekuritas',
    'EK': 'Eka Karya Sekuritas',
    'EL': 'Elang Sekuritas',
    'EM': 'Eka Mandiri Sekuritas',
    'EN': 'Enam Sembilan Sekuritas',
    'EO': 'Eko Oke Sekuritas',
    'EP': 'Eka Perdana Sekuritas',
    'EQ': 'Equity Development Sekuritas',
    'ER': 'Era Sekuritas',
    'ES': 'Esa Saja Sekuritas',
    'ET': 'Etana Sekuritas',
    'EU': 'Eureka Sekuritas',
    'EV': 'Evergreen Sekuritas',
    'EW': 'Eka Wira Sekuritas',
    'EX': 'Exchange Sekuritas',
    'EY': 'Eka Yasa Sekuritas',
    'FA': 'Fajar Sekuritas',
    'FB': 'Fauzi Bina Sekuritas',
    'FC': 'First Asia Capital',
    'FD': 'Fortuna Dana Sekuritas',
    'FE': 'Federasi Sekuritas',
    'FF': 'FIFGROUP',
    'FG': 'Fajar Gunawan Sekuritas',
    'FH': 'Fajar Harapan Sekuritas',
    'FI': 'Ficomindo',
    'FJ': 'Fajar Jaya Sekuritas',
    'FK': 'Fajar Karya Sekuritas',
    'FL': 'Flash Capital',
    'FM': 'Fajar Mandiri Sekuritas',
    'FN': 'Fajar Nusantara Sekuritas',
    'FO': 'Fortune Indonesia',
    'FP': 'Fajar Perdana Sekuritas',
    'FQ': 'Fajar Quantum Sekuritas',
    'FR': 'Fajar Raya Sekuritas',
    'FS': 'Fajar Sejahtera Sekuritas',
    'FT': 'Fajar Tiga Sekuritas',
    'FU': 'Fajar Unggul Sekuritas',
    'FV': 'Fajar Valuta Sekuritas',
    'FW': 'Fajar Wira Sekuritas',
    'FX': 'Fajar X Sekuritas',
    'FY': 'Fajar Yasa Sekuritas',
    'GA': 'Gain Capital',
    'GB': 'Gita Bina Sekuritas',
    'GC': 'Global Capital',
    'GD': 'Garda Sekuritas',
    'GE': 'Genta Equity',
    'GF': 'Global Fokus Sekuritas',
    'GG': 'Gading Ganda Sekuritas',
    'GH': 'Global Harapan Sekuritas',
    'GI': 'Global Investama',
    'GJ': 'Global Jaya Sekuritas',
    'GK': 'Global Karya Sekuritas',
    'GL': 'Globalindo',
    'GM': 'Gramedia Sekuritas',
    'GN': 'Guna Nasional Sekuritas',
    'GO': 'Go Optima Sekuritas',
    'GP': 'Global Perdana Sekuritas',
    'GQ': 'Global Quantum Sekuritas',
    'GR': 'Grahadipta Sekuritas',
    'GS': 'Goldman Sachs',
    'GT': 'Gatra Sekuritas',
    'GU': 'Guna Usaha Sekuritas',
    'GV': 'Global Valuta Sekuritas',
    'GW': 'Global Wira Sekuritas',
    'GX': 'Global X Sekuritas',
    'GY': 'Global Yasa Sekuritas',
    'HA': 'Harvest Capital',
    'HB': 'Hasta Bina Sekuritas',
    'HC': 'Hasta Capital',
    'HD': 'Hartindo Sekuritas',
    'HE': 'Henan Ekayasa Sekuritas',
    'HF': 'Henan Fokus Sekuritas',
    'HG': 'Henan Global Sekuritas',
    'HH': 'Henan Harapan Sekuritas',
    'HI': 'Henan Investama',
    'HJ': 'Henan Jaya Sekuritas',
    'HK': 'Henan Karya Sekuritas',
    'HL': 'Henan Lestari Sekuritas',
    'HM': 'Henan Mandiri Sekuritas',
    'HN': 'Henan Nasional Sekuritas',
    'HO': 'Henan Optimis Sekuritas',
    'HP': 'Henan Perdana Sekuritas',
    'HQ': 'Henan Quantum Sekuritas',
    'HR': 'Henan Raya Sekuritas',
    'HS': 'HSBC Sekuritas',
    'HT': 'Henan Trust Sekuritas',
    'HU': 'Henan Unggul Sekuritas',
    'HV': 'Henan Valuta Sekuritas',
    'HW': 'Henan Wira Sekuritas',
    'HX': 'Henan X Sekuritas',
    'HY': 'Henan Yasa Sekuritas',
    'IA': 'Indo Asia Sekuritas',
    'IB': 'Indo Bina Sekuritas',
    'IC': 'Indo Capital',
    'ID': 'Indo Dana Sekuritas',
    'IE': 'Indo Equity',
    'IF': 'Indo Fokus Sekuritas',
    'IG': 'Indo Global Sekuritas',
    'IH': 'Indo Harapan Sekuritas',
    'II': 'Indo Investama',
    'IJ': 'Indo Jaya Sekuritas',
    'IK': 'Indo Karya Sekuritas',
    'IL': 'Indo Lestari Sekuritas',
    'IM': 'Indo Mandiri Sekuritas',
    'IN': 'Indo Nasional Sekuritas',
    'IO': 'Indo Optimis Sekuritas',
    'IP': 'Indo Premier Sekuritas',
    'IQ': 'Indo Quantum Sekuritas',
    'IR': 'Indo Raya Sekuritas',
    'IS': 'Indo Sekuritas',
    'IT': 'Indo Trust Sekuritas',
    'IU': 'Indo Unggul Sekuritas',
    'IV': 'Indo Valuta Sekuritas',
    'IW': 'Indo Wira Sekuritas',
    'IX': 'Indo X Sekuritas',
    'IY': 'Indo Yasa Sekuritas',
    'JA': 'Jasa Akbar Sekuritas',
    'JB': 'Jaya Bina Sekuritas',
    'JC': 'Jaya Capital',
    'JD': 'Jaya Dana Sekuritas',
    'JE': 'Jaya Equity',
    'JF': 'Jaya Fokus Sekuritas',
    'JG': 'Jaya Global Sekuritas',
    'JH': 'Jaya Harapan Sekuritas',
    'JI': 'Jaya Investama',
    'JJ': 'Jaya Jaya Sekuritas',
    'JK': 'Jaya Karya Sekuritas',
    'JL': 'Jaya Lestari Sekuritas',
    'JM': 'JPMorgan Sekuritas',
    'JN': 'Jaya Nasional Sekuritas',
    'JO': 'Jaya Optimis Sekuritas',
    'JP': 'Jaya Perdana Sekuritas',
    'JQ': 'Jaya Quantum Sekuritas',
    'JR': 'Jaya Raya Sekuritas',
    'JS': 'Jaya Sejahtera Sekuritas',
    'JT': 'Jaya Trust Sekuritas',
    'JU': 'Jaya Unggul Sekuritas',
    'JV': 'Jaya Valuta Sekuritas',
    'JW': 'Jaya Wira Sekuritas',
    'JX': 'Jaya X Sekuritas',
    'JY': 'Jaya Yasa Sekuritas',
    'KA': 'Karya Arah Sekuritas',
    'KB': 'Karya Bina Sekuritas',
    'KC': 'Karya Capital',
    'KD': 'Karya Dana Sekuritas',
    'KE': 'Karya Equity',
    'KF': 'Karya Fokus Sekuritas',
    'KG': 'Karya Global Sekuritas',
    'KH': 'Karya Harapan Sekuritas',
    'KI': 'Karya Investama',
    'KJ': 'Karya Jaya Sekuritas',
    'KK': 'Karya Karya Sekuritas',
    'KL': 'Karya Lestari Sekuritas',
    'KM': 'Karya Mandiri Sekuritas',
    'KN': 'Karya Nasional Sekuritas',
    'KO': 'Karya Optimis Sekuritas',
    'KP': 'Karya Perdana Sekuritas',
    'KQ': 'Karya Quantum Sekuritas',
    'KR': 'Karya Raya Sekuritas',
    'KS': 'Karya Sejahtera Sekuritas',
    'KT': 'Karya Trust Sekuritas',
    'KU': 'Karya Unggul Sekuritas',
    'KV': 'Karya Valuta Sekuritas',
    'KW': 'Karya Wira Sekuritas',
    'KX': 'Karya X Sekuritas',
    'KY': 'Karya Yasa Sekuritas',
    'LA': 'Lautandhana Sekuritas',
    'LB': 'Laba Bina Sekuritas',
    'LC': 'Laba Capital',
    'LD': 'Laba Dana Sekuritas',
    'LE': 'Laba Equity',
    'LF': 'Laba Fokus Sekuritas',
    'LG': 'Laba Global Sekuritas',
    'LH': 'Laba Harapan Sekuritas',
    'LI': 'Laba Investama',
    'LJ': 'Laba Jaya Sekuritas',
    'LK': 'Laba Karya Sekuritas',
    'LL': 'Laba Lestari Sekuritas',
    'LM': 'Laba Mandiri Sekuritas',
    'LN': 'Laba Nasional Sekuritas',
    'LO': 'Laba Optimis Sekuritas',
    'LP': 'Laba Perdana Sekuritas',
    'LQ': 'Laba Quantum Sekuritas',
    'LR': 'Laba Raya Sekuritas',
    'LS': 'Laba Sejahtera Sekuritas',
    'LT': 'Laba Trust Sekuritas',
    'LU': 'Laba Unggul Sekuritas',
    'LV': 'Laba Valuta Sekuritas',
    'LW': 'Laba Wira Sekuritas',
    'LX': 'Laba X Sekuritas',
    'LY': 'Laba Yasa Sekuritas',
    'MA': 'Mandiri Sekuritas',
    'MB': 'Mega Bina Sekuritas',
    'MC': 'Mega Capital',
    'MD': 'Mega Dana Sekuritas',
    'ME': 'Mega Equity',
    'MF': 'Mega Fokus Sekuritas',
    'MG': 'Mega Global Sekuritas',
    'MH': 'Mega Harapan Sekuritas',
    'MI': 'Mega Investama',
    'MJ': 'Mega Jaya Sekuritas',
    'MK': 'Mega Karya Sekuritas',
    'ML': 'Mega Lestari Sekuritas',
    'MM': 'Mega Mandiri Sekuritas',
    'MN': 'Mega Nasional Sekuritas',
    'MO': 'Morgan Stanley Sekuritas',
    'MP': 'Mega Perdana Sekuritas',
    'MQ': 'Mega Quantum Sekuritas',
    'MR': 'Mega Raya Sekuritas',
    'MS': 'Mega Sejahtera Sekuritas',
    'MT': 'Mega Trust Sekuritas',
    'MU': 'Mega Unggul Sekuritas',
    'MV': 'Mega Valuta Sekuritas',
    'MW': 'Mega Wira Sekuritas',
    'MX': 'Macquarie Sekuritas',
    'MY': 'Maybank Sekuritas',
    'MZ': 'Mizuho Sekuritas',
    'NA': 'Naga Sekuritas',
    'NB': 'Noble Bina Sekuritas',
    'NC': 'NC Sekuritas',
    'ND': 'Noble Dana Sekuritas',
    'NE': 'Noble Equity',
    'NF': 'Noble Fokus Sekuritas',
    'NG': 'Noble Global Sekuritas',
    'NH': 'NH-CORINDO Sekuritas',
    'NI': 'Noble Investama',
    'NJ': 'Noble Jaya Sekuritas',
    'NK': 'Noble Karya Sekuritas',
    'NL': 'Noble Lestari Sekuritas',
    'NM': 'Nomura Sekuritas',
    'NN': 'Noble Nasional Sekuritas',
    'NO': 'Noble Optimis Sekuritas',
    'NP': 'Noble Perdana Sekuritas',
    'NQ': 'Noble Quantum Sekuritas',
    'NR': 'Noble Raya Sekuritas',
    'NS': 'Noble Sejahtera Sekuritas',
    'NT': 'Noble Trust Sekuritas',
    'NU': 'Noble Unggul Sekuritas',
    'NV': 'Noble Valuta Sekuritas',
    'NW': 'Noble Wira Sekuritas',
    'NX': 'Noble X Sekuritas',
    'NY': 'Noble Yasa Sekuritas',
    'OC': 'Oceania Capital',
    'OD': 'Oceania Dana Sekuritas',
    'OE': 'Oceania Equity',
    'OF': 'Oceania Fokus Sekuritas',
    'OG': 'Oceania Global Sekuritas',
    'OH': 'Oceania Harapan Sekuritas',
    'OI': 'Oceania Investama',
    'OJ': 'Oceania Jaya Sekuritas',
    'OK': 'Oceania Karya Sekuritas',
    'OL': 'Oceania Lestari Sekuritas',
    'OM': 'Oceania Mandiri Sekuritas',
    'ON': 'Oceania Nasional Sekuritas',
    'OO': 'Oceania Optimis Sekuritas',
    'OP': 'Oceania Perdana Sekuritas',
    'OQ': 'Oceania Quantum Sekuritas',
    'OR': 'Oceania Raya Sekuritas',
    'OS': 'Oceania Sejahtera Sekuritas',
    'OT': 'Oceania Trust Sekuritas',
    'OU': 'Oceania Unggul Sekuritas',
    'OV': 'Oceania Valuta Sekuritas',
    'OW': 'Oceania Wira Sekuritas',
    'OX': 'Oceania X Sekuritas',
    'OY': 'Oceania Yasa Sekuritas',
    'PA': 'Panin Sekuritas',
    'PB': 'Panin Bina Sekuritas',
    'PC': 'Panin Capital',
    'PD': 'Panin Dana Sekuritas',
    'PE': 'Panin Equity',
    'PF': 'Panin Fokus Sekuritas',
    'PG': 'Panin Global Sekuritas',
    'PH': 'Panin Harapan Sekuritas',
    'PI': 'Panin Investama',
    'PJ': 'Panin Jaya Sekuritas',
    'PK': 'Panin Karya Sekuritas',
    'PL': 'Panin Lestari Sekuritas',
    'PM': 'Panin Mandiri Sekuritas',
    'PN': 'Panin Nasional Sekuritas',
    'PO': 'Panin Optimis Sekuritas',
    'PP': 'Panin Perdana Sekuritas',
    'PQ': 'Panin Quantum Sekuritas',
    'PR': 'Panin Raya Sekuritas',
    'PS': 'Panin Sejahtera Sekuritas',
    'PT': 'Panin Trust Sekuritas',
    'PU': 'Panin Unggul Sekuritas',
    'PV': 'Panin Valuta Sekuritas',
    'PW': 'Panin Wira Sekuritas',
    'PX': 'Panin X Sekuritas',
    'PY': 'Panin Yasa Sekuritas',
    'RA': 'Reliance Sekuritas',
    'RB': 'Resona Bina Sekuritas',
    'RC': 'Resona Capital',
    'RD': 'Resona Dana Sekuritas',
    'RE': 'Resona Equity',
    'RF': 'Resona Fokus Sekuritas',
    'RG': 'Resona Global Sekuritas',
    'RH': 'Resona Harapan Sekuritas',
    'RI': 'Resona Investama',
    'RJ': 'Resona Jaya Sekuritas',
    'RK': 'Resona Karya Sekuritas',
    'RL': 'Resona Lestari Sekuritas',
    'RM': 'Resona Mandiri Sekuritas',
    'RN': 'Resona Nasional Sekuritas',
    'RO': 'Resona Optimis Sekuritas',
    'RP': 'Resona Perdana Sekuritas',
    'RQ': 'Resona Quantum Sekuritas',
    'RR': 'Resona Raya Sekuritas',
    'RS': 'Resona Sejahtera Sekuritas',
    'RT': 'Resona Trust Sekuritas',
    'RU': 'Resona Unggul Sekuritas',
    'RV': 'Resona Valuta Sekuritas',
    'RW': 'Resona Wira Sekuritas',
    'RX': 'Resona X Sekuritas',
    'RY': 'Resona Yasa Sekuritas',
    'SA': 'Samuel Sekuritas',
    'SB': 'Sinar Bina Sekuritas',
    'SC': 'Sinar Capital',
    'SD': 'Sinar Dana Sekuritas',
    'SE': 'Sinar Equity',
    'SF': 'Sinar Fokus Sekuritas',
    'SG': 'Sinar Global Sekuritas',
    'SH': 'Sinar Harapan Sekuritas',
    'SI': 'Sinar Investama',
    'SJ': 'Sinar Jaya Sekuritas',
    'SK': 'Sinar Karya Sekuritas',
    'SL': 'Sinar Lestari Sekuritas',
    'SM': 'Sinar Mandiri Sekuritas',
    'SN': 'Sinar Nasional Sekuritas',
    'SO': 'Sinar Optimis Sekuritas',
    'SP': 'Sinar Perdana Sekuritas',
    'SQ': 'Sinar Quantum Sekuritas',
    'SR': 'Sinar Raya Sekuritas',
    'SS': 'Sinar Sejahtera Sekuritas',
    'ST': 'Standard Chartered Sekuritas',
    'SU': 'Sinar Unggul Sekuritas',
    'SV': 'Sinar Valuta Sekuritas',
    'SW': 'Sinar Wira Sekuritas',
    'SX': 'Sinar X Sekuritas',
    'SY': 'Sinar Yasa Sekuritas',
    'TA': 'Trimegah Sekuritas',
    'TB': 'Trimegah Bina Sekuritas',
    'TC': 'Trimegah Capital',
    'TD': 'Trimegah Dana Sekuritas',
    'TE': 'Trimegah Equity',
    'TF': 'Trimegah Fokus Sekuritas',
    'TG': 'Trimegah Global Sekuritas',
    'TH': 'Trimegah Harapan Sekuritas',
    'TI': 'Trimegah Investama',
    'TJ': 'Trimegah Jaya Sekuritas',
    'TK': 'Trimegah Karya Sekuritas',
    'TL': 'Trimegah Lestari Sekuritas',
    'TM': 'Trimegah Mandiri Sekuritas',
    'TN': 'Trimegah Nasional Sekuritas',
    'TO': 'Trimegah Optimis Sekuritas',
    'TP': 'Trimegah Perdana Sekuritas',
    'TQ': 'Trimegah Quantum Sekuritas',
    'TR': 'Trimegah Raya Sekuritas',
    'TS': 'Trimegah Sejahtera Sekuritas',
    'TT': 'Trimegah Trust Sekuritas',
    'TU': 'Trimegah Unggul Sekuritas',
    'TV': 'Trimegah Valuta Sekuritas',
    'TW': 'Trimegah Wira Sekuritas',
    'TX': 'Trimegah X Sekuritas',
    'TY': 'Trimegah Yasa Sekuritas',
    'UB': 'UBS Sekuritas',
    'UC': 'UBS Capital',
    'UD': 'UBS Dana Sekuritas',
    'UE': 'UBS Equity',
    'UF': 'UBS Fokus Sekuritas',
    'UG': 'UBS Global Sekuritas',
    'UH': 'UBS Harapan Sekuritas',
    'UI': 'UBS Investama',
    'UJ': 'UBS Jaya Sekuritas',
    'UK': 'UBS Karya Sekuritas',
    'UL': 'UBS Lestari Sekuritas',
    'UM': 'UBS Mandiri Sekuritas',
    'UN': 'UBS Nasional Sekuritas',
    'UO': 'UBS Optimis Sekuritas',
    'UP': 'UBS Perdana Sekuritas',
    'UQ': 'UBS Quantum Sekuritas',
    'UR': 'UBS Raya Sekuritas',
    'US': 'UBS Sejahtera Sekuritas',
    'UT': 'UBS Trust Sekuritas',
    'UU': 'UBS Unggul Sekuritas',
    'UV': 'UBS Valuta Sekuritas',
    'UW': 'UBS Wira Sekuritas',
    'UX': 'UBS X Sekuritas',
    'UY': 'UBS Yasa Sekuritas',
    'VA': 'Valbury Sekuritas',
    'VB': 'Valbury Bina Sekuritas',
    'VC': 'Valbury Capital',
    'VD': 'Valbury Dana Sekuritas',
    'VE': 'Valbury Equity',
    'VF': 'Valbury Fokus Sekuritas',
    'VG': 'Valbury Global Sekuritas',
    'VH': 'Valbury Harapan Sekuritas',
    'VI': 'Valbury Investama',
    'VJ': 'Valbury Jaya Sekuritas',
    'VK': 'Valbury Karya Sekuritas',
    'VL': 'Valbury Lestari Sekuritas',
    'VM': 'Valbury Mandiri Sekuritas',
    'VN': 'Valbury Nasional Sekuritas',
    'VO': 'Valbury Optimis Sekuritas',
    'VP': 'Valbury Perdana Sekuritas',
    'VQ': 'Valbury Quantum Sekuritas',
    'VR': 'Valbury Raya Sekuritas',
    'VS': 'Valbury Sejahtera Sekuritas',
    'VT': 'Valbury Trust Sekuritas',
    'VU': 'Valbury Unggul Sekuritas',
    'VV': 'Valbury Valuta Sekuritas',
    'VW': 'Valbury Wira Sekuritas',
    'VX': 'Valbury X Sekuritas',
    'VY': 'Valbury Yasa Sekuritas',
    'WA': 'Wahana Bina Sekuritas',
    'WB': 'Wahana Bina Sekuritas',
    'WC': 'Wahana Capital',
    'WD': 'Wahana Dana Sekuritas',
    'WE': 'Wahana Equity',
    'WF': 'Wahana Fokus Sekuritas',
    'WG': 'Wahana Global Sekuritas',
    'WH': 'Wahana Harapan Sekuritas',
    'WI': 'Wahana Investama',
    'WJ': 'Wahana Jaya Sekuritas',
    'WK': 'Wahana Karya Sekuritas',
    'WL': 'Wahana Lestari Sekuritas',
    'WM': 'Wahana Mandiri Sekuritas',
    'WN': 'Wahana Nasional Sekuritas',
    'WO': 'Wahana Optimis Sekuritas',
    'WP': 'Wahana Perdana Sekuritas',
    'WQ': 'Wahana Quantum Sekuritas',
    'WR': 'Wahana Raya Sekuritas',
    'WS': 'Wahana Sejahtera Sekuritas',
    'WT': 'Wahana Trust Sekuritas',
    'WU': 'Wahana Unggul Sekuritas',
    'WV': 'Wahana Valuta Sekuritas',
    'WW': 'Wahana Wira Sekuritas',
    'WX': 'Wahana X Sekuritas',
    'WY': 'Wahana Yasa Sekuritas',
    'XA': 'X Bina Sekuritas',
    'XB': 'X Bina Sekuritas',
    'XC': 'X Capital',
    'XD': 'X Dana Sekuritas',
    'XE': 'X Equity',
    'XF': 'X Fokus Sekuritas',
    'XG': 'X Global Sekuritas',
    'XH': 'X Harapan Sekuritas',
    'XI': 'X Investama',
    'XJ': 'X Jaya Sekuritas',
    'XK': 'X Karya Sekuritas',
    'XL': 'XL Sekuritas',
    'XM': 'X Mandiri Sekuritas',
    'XN': 'X Nasional Sekuritas',
    'XO': 'X Optimis Sekuritas',
    'XP': 'X Perdana Sekuritas',
    'XQ': 'X Quantum Sekuritas',
    'XR': 'X Raya Sekuritas',
    'XS': 'X Sejahtera Sekuritas',
    'XT': 'X Trust Sekuritas',
    'XU': 'X Unggul Sekuritas',
    'XV': 'X Valuta Sekuritas',
    'XW': 'X Wira Sekuritas',
    'XX': 'X X Sekuritas',
    'XY': 'X Yasa Sekuritas',
    'YP': 'Yoga Pratama Sekuritas',
    'YQ': 'Yoga Quantum Sekuritas',
    'YR': 'Yoga Raya Sekuritas',
    'YS': 'Yoga Sejahtera Sekuritas',
    'YT': 'Yoga Trust Sekuritas',
    'YU': 'Yoga Unggul Sekuritas',
    'YV': 'Yoga Valuta Sekuritas',
    'YW': 'Yoga Wira Sekuritas',
    'YX': 'Yoga X Sekuritas',
    'YY': 'Yoga Yasa Sekuritas',
    'ZA': 'Z Bina Sekuritas',
    'ZB': 'Z Bina Sekuritas',
    'ZC': 'Z Capital',
    'ZD': 'Z Dana Sekuritas',
    'ZE': 'Z Equity',
    'ZF': 'Z Fokus Sekuritas',
    'ZG': 'Z Global Sekuritas',
    'ZH': 'Z Harapan Sekuritas',
    'ZI': 'Z Investama',
    'ZJ': 'Z Jaya Sekuritas',
    'ZK': 'Z Karya Sekuritas',
    'ZL': 'Z Lestari Sekuritas',
    'ZM': 'Z Mandiri Sekuritas',
    'ZN': 'Z Nasional Sekuritas',
    'ZO': 'Z Optimis Sekuritas',
    'ZP': 'Z Perdana Sekuritas',
    'ZQ': 'Z Quantum Sekuritas',
    'ZR': 'Z Raya Sekuritas',
    'ZS': 'Z Sejahtera Sekuritas',
    'ZT': 'Z Trust Sekuritas',
    'ZU': 'Z Unggul Sekuritas',
    'ZV': 'Z Valuta Sekuritas',
    'ZW': 'Z Wira Sekuritas',
    'ZX': 'Z X Sekuritas',
    'ZY': 'Z Yasa Sekuritas',
};

export function getBrokerName(code: string): string {
    return BROKER_CODES[code.toUpperCase()] || code;
}
